### ISSUE TITLE
RidesAndFaresSolution.scala Questions

### ISSUE THREAD

**Issue by MJeremy2017** [ververica/flink-training-exercises#45]
Hi, I have some confusions on `connect` operations in flink, wonder if I can ask here:
1. the result intends to collect (ride, fare) for each orderId, why after collecting, only fare state is cleared? Since the result for that orderId has been joined and collected, shouldn't all states be cleared out?
2. suppose there is one-to-many relationships, where ride -> fare1 and fare2. Then if I don't clear the state, will it emit (ride, fare1) and (ride, fare2)?

Thanks in advance!

**Comment by alpinegizmo** [comment]
@MJeremy2017 Sorry your questions were overlooked:

1. Either the ride or the fare arrives first, and is saved in state. For example, suppose the ride arrives first, and is saved. When the matching fare arrives, the result is collected and the state for the ride that was previously saved needs to be cleared. Since the fare was never stored, it doesn't need to be cleared. 

2. Yes, but only if the ride was processed first, in which case it will be in the state that isn't cleared. Otherwise fare1 would be in state, and the ride would be lost.
