### ISSUE TITLE
where is the data set 

### ISSUE THREAD

**Issue by ThomasSunKai** [ververica/flink-training-exercises#47]
when I do the example of CarEventSort.java , i failed to find the corresponding data set for this example, this example is very important, so how can i find them? many thx!

**Comment by sjwiesman** [comment]
Hi @ThomasSunKai, 

Take a look at the training site. 

https://training.ververica.com/setup/taxiData.html

**Comment by alpinegizmo** [comment]
@ThomasSunKai @sjwiesman The exercise connected with that example has been deprecated because it's not a very good example of how to do a sort. But you'll find more info about it, including pointers to the connected car dataset it uses, at https://training.ververica.com/exercises/connectedCar.html.

For more on the subject of sorting streams with Flink, see https://stackoverflow.com/questions/59468154/how-to-sort-an-out-of-order-event-time-stream-using-flink.

**Comment by ThomasSunKai** [comment]
Hi @alpinegizmo ,many thanks to your answer, i have been following ververica all examples one by one, this seems to be a  good one with watermark, but not a lot of detail of this exmaple, i'm in the middle now and stuck here , it is not a good idea to just quit, by the way i will go to the other links you recommend!
